### ISSUE TITLE
Add font-lock for strings inside lists

### ISSUE THREAD

**Issue by CSRaghunandan** [Wilfred/helpful#100]
Refer to the below screenshot:
<img width="1678" alt="screen shot 2018-03-02 at 3 46 30 pm" src="https://user-images.githubusercontent.com/5226809/36894456-63d72444-1e31-11e8-8219-7ab663258c73.png">

Also, maybe you'd want to show the bytecode like `*help*` buffer does instead of showing a bunch of escape sequences?

**Comment by Wilfred** [comment]
Fixed in #144.
