### ISSUE TITLE
helpful-variable doesn't clean up the buffers it opens

### ISSUE THREAD

**Issue by hlissner** [Wilfred/helpful#101]
`find-definition-noselect` In `helpful--definition` opens the buffer for `sym` (on [line 997](https://github.com/Wilfred/helpful/blob/master/helpful.el#L997)), but does not kill the buffer afterwards.

Perhaps another `(-contains-p initial-buffers buf)` check is necessary? One exists in `helpful--defintion` for callables, but not for non-callables.

## Steps to reproduce

1. `M-x helpful-variable RET after-init-hook`
2. `M-x list-buffers`
3. `startup.el.gz` remains in the buffer list

## System Information

Tested on Emacs 25.3 and 27.0.51, on MacOS and Arch Linux, in a blank Emacs session (`-Q`).

**Comment by Wilfred** [comment]
Great bug report, thank you :)

This should now be fixed.
