### ISSUE TITLE
Ivy integration?

### ISSUE THREAD

**Issue by seagle0128** [Wilfred/helpful#105]
I like `helpful` very much. Can you please integrate with `ivy` (or `counsel`)? The link is https://github.com/abo-abo/swiper. That would be great and easy to use. Thanks!

**Comment by Wilfred** [comment]
Helpful uses whatever minibuffer completion is active, so it should work with ivy or helm. I actually use ivy :)

Did you mean minibuffer completion in general, or did you have a specific ivy feature in mind?

**Comment by seagle0128** [comment]
Thanks for the quick reply!
It does work after `ivy-mode` is enabled. But I think it's not good integration, e.g. `smex` doesn't work well with `helpful`. That's what `counsel` does.

**Comment by Wilfred** [comment]
What integration were you thinking of how? How would you like things to be different?

**Comment by seagle0128** [comment]
I checked the codes of `counsel`. `smex` is only enabled in `counsel-M-x`. `smex` will record the frequencies of the used candidates.

The behaviors of `helpful-callable` and others are similar with `counsel-describe-xxx`. The only different is the list sequence. It doesn't matter and I am closing it. Thanks!
