### ISSUE TITLE
Autoload: [Arg list not available until function definition is loaded.]

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#117]
Here's what I get for `make-display-table`:

`helpful-callable`:

```
make-display-table is a function defined in disp-table.el.gz.

Function Signature
(make-display-table [Arg list not available until function definition is loaded.])

Function Documentation
Return a new, empty display table.

...

Source Code
;; Defined in /Applications/Emacs.app/Contents/Resources/lisp/disp-table.el.gz
;;;###autoload
(defun make-display-table ()
  "Return a new, empty display table."
  (make-char-table 'display-table nil))
```

`describe-function`

```
make-display-table is an autoloaded Lisp function in ‘disp-table.el’.

[Arg list not available until function definition is loaded.]

Return a new, empty display table.
```

Strange, right? But then if I go in and evaluate the function, they both show the real signature.

```
Function Signature
(make-display-table)
```

```
make-display-table is a Lisp function.

(make-display-table)
```

Anyway, I guess this case should be handled by the helpful function signature display.

**Comment by Wilfred** [comment]
Yep, so we're consistent with describe-function here. Emacs doesn't load libraries until they're needed, saving startup time but it means the function object is just a placeholder with argument information.

I think we should just load the function if you try to inspect it. That seems more useful.

**Comment by Wilfred** [comment]
Looks like Emacs does load files in some circumstances: `describe-function` on `fortran-mode` loads the file so it can render `fortran-mode-map` in the help buffer.

**Comment by nickdrozd** [comment]
This is related I think.

```
elp-instrument-list is an interactive function defined in elp.el.gz.

Signature
(elp-instrument-list &optional LIST)

Documentation
Instrument, for profiling, all functions in elp-function-list.

Use optional LIST if provided instead.
If called interactively, prompt for LIST in the minibuffer;
type "nil" to use elp-function-list.
```

On startup, the variable `elp-function-list` is highlighted but not linked, as it hasn't been loaded yet. But if you run `elp-instrument-list` and then check again, it will be linked. I think it's part of elp's API, so I don't understand why it isn't autoloaded. The whole thing feels strange.

**Comment by Wilfred** [comment]
Yep, so helpful considers whether a variable is bound when highlighting docstrings: https://github.com/wilfred/helpful/blob/master/helpful.el#L718-L720

If we force the loading of functions, we'll have the full argument list and the proper highlighting of the docstring. I don't see any downside.

**Comment by Wilfred** [comment]
Turns out that this is configurable (how Emacsy!) in core too, using `help-enable-auto-load`.

**Comment by nickdrozd** [comment]
Another example: `(helpful-function 'tetris)` fails with `(void-variable tetris-mode-map)`, unless `tetris` has already been loaded, in which case it works fine.

Relevant code from `help-fns.el`:

```emacs-lisp
    ;; If the function is autoloaded, and its docstring has
    ;; key substitution constructs, load the library.
    (and (autoloadp real-def) doc-raw
         help-enable-auto-load
         (string-match "\\([^\\]=\\|[^=]\\|\\`\\)\\\\[[{<]" doc-raw)
         (autoload-do-load real-def))
```

**Comment by Wilfred** [comment]
Thanks! The sample code from help-fns.el was particularly, well, helpful :)
