### ISSUE TITLE
Support displaying key bindings in helpful-variable

### ISSUE THREAD

**Issue by wyuenho** [Wilfred/helpful#122]
Right now `helpful-variable` only shows a keymaps only shows the ASCII key codes for a keymap like the built-in help. It would be nice if `helpful-variable` would display a formatted definition similar to how `helpful-command` already does when it sees a `\\{keymap}` in the docstring.

**Comment by wyuenho** [comment]
I mean turn this from `helpful-variable`

```emacs-lisp
company-active-map is a variable defined in company.el.

Variable Documentation
Keymap that is enabled during an active completion.

Value
(keymap
 (16 . company-select-previous)
 (14 . company-select-next)
 (19 . company-search-candidates)
 (23 . company-show-location)
 (8 . company-show-doc-buffer)
 (f1 . company-show-doc-buffer)
 (9 . company-complete-common)
 (tab . company-complete-common)
...
```

into something nicely formatted like you already do for commands

```
Variable Documentation
Keymap that is enabled during an active completion.

C-n company-select-previous
C-p company-select-next
...
```

**Comment by alphapapa** [comment]
This would be really, er...helpful!  :)

**Comment by mpereira** [comment]
I agree this would be useful to have in `helpful`. Right now I'm fallbacking to `describe-keymap` from `help-fns+`, which does exactly what you want @wyuenho: https://github.com/emacsmirror/help-fns-plus/blob/a21b319de476bfbaad32e349309b6b5148608d63/help-fns%2B.el#L2887

**Comment by mpereira** [comment]
@wyuenho more specifically:

```elisp
;; Modified https://www.emacswiki.org/emacs/DescribeThingAtPoint.
;; Depends on helpful for `helpful-function' and `helpful-variable'.
;; Depends on help-fns+ for `describe-keymap'.
(defun mpereira/describe-thing-at-point ()
  "Show a help buffer for the symbol at point.
  This checks in turn:
  -- for a function name where point is
  -- for a keymap name where point is
  -- for a variable name where point is
  -- for a surrounding function call"
  (interactive)
  (let (sym)
    (cond ((setq sym (ignore-errors
                       (with-syntax-table emacs-lisp-mode-syntax-table
                         (save-excursion
                           (or (not (zerop (skip-syntax-backward "_w")))
                               (eq (char-syntax (char-after (point))) ?w)
                               (eq (char-syntax (char-after (point))) ?_)
                               (forward-sexp -1))
                           (skip-chars-forward "`'")
                           (let ((obj (read (current-buffer))))
                             (and (symbolp obj) (fboundp obj) obj))))))
           (helpful-function sym))
          ((setq sym (variable-at-point)) (if (keymapp (symbol-value sym))
                                              (describe-keymap sym)
                                            (helpful-variable sym)))
          ((setq sym (function-at-point)) (helpful-function sym)))))
```

**Comment by Wilfred** [comment]
OK, I've added a 'pretty view' for keymaps (and for strings too). By default it still shows the literal view, but you can press the button to see human-friendly descriptions of the keybindings, and get links to the commands bound.

The advantage of the literal view is that you can see which commands are remapped, and you can see when keymaps are inherited.

Please have a play with it and tell me what you think. We could consider making the pretty view the default, but I worry it'd be slightly confusing. I'm open to feedback :)
