### ISSUE TITLE
helpful-variable prompts for file-local variables

### ISSUE THREAD

**Issue by hlissner** [Wilfred/helpful#123]
`helpful-variable` bombards me with prompts about unsafe file variables (once per section in the helpful buffer, apparently).

The issue originates from `helpful--definition`. `enable-local-variables` is let-bound to nil [for callables](https://github.com/Wilfred/helpful/blob/master/helpful.el#L1037), but not [for non-callables](https://github.com/Wilfred/helpful/blob/master/helpful.el#L1074-L1080).

### Steps to reproduce

Put the following in a blank file. Save and evaluate it:

```elisp
(defvar foo-bar t)

;; Local Variables:
;; coding: utf-8
;; eval: (message "Hello")
;; End:
```

Then `M-x helpful-variable RET foo-bar`

**Comment by Wilfred** [comment]
Excellent bug report, thank you very much! :)

I believe this is properly fixed now, but let me know if not.
