### ISSUE TITLE
Custom group is child of itself

### ISSUE THREAD

**Issue by sheijk** [Wilfred/helpful#125]
```elisp
(defgroup helpful nil
  "A rich help system with contextual information."
  :group 'helpful)
```
this makes the helpful group a child of itself. Use *M-x, customize-group, helpful* and you'll see *helpful* listed as both parent group and subgroup. I'd suggest making *'help* the parent group so helpful will show up there with everything else related to help

**Comment by Wilfred** [comment]
Thanks :)
