### ISSUE TITLE
Enhancement: Integration with helm-apropos code example

### ISSUE THREAD

**Issue by dfeich** [Wilfred/helpful#126]
First, I would like to thank you for providing this really helpful package! I am already using it a lot.

Since I did not want to fully replace the default help functions, I decided to add it to `helm-apropos` which anyhow is my primary gateway to the help system. Maybe others would like to benefit from this as well, so I send you the code. If you want to put it in the docu, change the function names to whatever fits best (I use the `dfeich/...` namespace to track my own config modifications).

I had to define a macro to define advices for the helm functions that produce these particular sources on the fly.

```emacs-lisp
(defmacro dfeich/helm-add-action-to-sourcefn (srcfn name func)
  "Adds an action to a helm source-producing function through advice."
  (let ((advfn (make-symbol (concat "dfeich/" (symbol-name srcfn)))))
    ;; The default selection is given in the first arg
    `(progn (defun ,advfn (origfn &rest args)
	      ;; (message (pp-to-string args))
	      (let* ((source (apply (list origfn (car args))))
		     (actions (alist-get 'action source)))
		(setf (alist-get 'action source)
		      (append actions (list (cons ,name ,func))))
		source))
	    (advice-add (quote,srcfn) :around (quote ,advfn)))))


(use-package helpful :ensure t
  :config (eval-after-load 'helm-elisp
	    (progn
	      (dfeich/helm-add-action-to-sourcefn helm-def-source--emacs-commands
						  "helpful-command"
						  (lambda (sel)
						    (funcall-interactively 'helpful-command (intern sel))))

	      (dfeich/helm-add-action-to-sourcefn helm-def-source--emacs-functions
						  "helpful-function"
						  (lambda (sel)
						    (funcall-interactively 'helpful-function (intern sel))))

	      (dfeich/helm-add-action-to-sourcefn helm-def-source--emacs-variables
						  "helpful-variable"
						  (lambda (sel)
						    (funcall-interactively 'helpful-variable (intern sel)))))))
```

**Comment by Wilfred** [comment]
Thanks for sharing!

I'm afraid that I don't use helm. I think your extension is neat, and if you release it is a separate package I will definitely link to it.

I don't think there's any action for me to take at the moment, so I'm going to close this. Thanks again :)
