### ISSUE TITLE
Error when looking up edebug-mode.

### ISSUE THREAD

**Issue by phoenixanimations** [Wilfred/helpful#133]
Currently on helpful-20180630.257, Version: 0.12
When doing emacs -Q:
```
(package-initialize)
(require 'helpful)
(global-set-key (kbd "C-h f") 'helpful-callable)
```
If you do `C-h f edebug-mode` you will receive an error:
`helpful--keymap-keys: Wrong type argument: listp, #[0 "ÀÁ!" [edebug-set-breakpoint t] 2 nil nil]` Haven't had time to debug why exactly, just wanted to let you guys know. Might be related to #118 but maybe not.

**Comment by nickdrozd** [comment]
Nice. Looks like `describe-function` is confused too:
```
C-c C-c		edebug-go-mode
C-c C-d		edebug-unset-breakpoint
C-c C-l		edebug-where
C-c C-n		edebug-next-mode
C-c C-s		edebug-step-mode
C-c C-t		??
```

That section of the `edebug-mode-map` is set with a lambda:

```
    (define-key map "\C-x " 'edebug-set-breakpoint)
    (define-key map "\C-c\C-d" 'edebug-unset-breakpoint)
    (define-key map "\C-c\C-t"
      (lambda () (interactive) (edebug-set-breakpoint t)))
    (define-key map "\C-c\C-l" 'edebug-where)
```

And that lambda gets compiled into that weird array thing:

```
ELISP> (byte-compile '(lambda () (interactive) (edebug-set-breakpoint t)))
#[nil "\300\301!\207"
      [edebug-set-breakpoint t]
      2 nil nil]

ELISP> (type-of *)
compiled-function
```

**Comment by nickdrozd** [comment]
A similar error can be triggered by entering `edebug-mode` and running `helpful-key` <kbd>C-c C-t</kbd>.

**Comment by Wilfred** [comment]
Should be fixed :)
