### ISSUE TITLE
Add helpful-key

### ISSUE THREAD

**Issue by spatz** [Wilfred/helpful#14]
Please add a function that replaces `describe-key` and shows `helpful-function` for the pressed key.

**Comment by Dickby** [comment]
it should also replace help-function, and help-variable.

**Comment by vkazanov** [comment]
A global minor mode would do?

**Comment by Dickby** [comment]
helpful-at-point could work for variables too.
And how about helpful-apropos?

**Comment by Wilfred** [comment]
What would you expect `helpful-apropos` to do?

**Comment by Dickby** [comment]
I thougt of an combination of the existing helpful functions, to search for any symbol.
Isn't the original `apropos` like that?

**Comment by Wilfred** [comment]
Would you mind opening a separate issue for `helpful-apropos`?
