### ISSUE TITLE
Idea: link to builtin Help from Helpful buffer

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#146]
If I run into something in a Helpful buffer that seems fishy (say, it tells me that `rename-buffer` has no source file), I always run the equivalent builtin Help command (`describe-function`, etc) to see what it has to say. It would be convenient to have a button or something to do this.

**Comment by Wilfred** [comment]
I don't think this is a good fit for Helpful: it's certainly useful for debugging and reflecting on the features, but ideally a user should never need to fall back to the default Emacs functionality. The number of buttons in Helpful buffers is growing, and I'm reluctant to add more if they don't enhance core functionality.

On the plus side, this is definitely something you could add to your own config :). Something like this should do the trick:

```emacs-lisp
(defun wh/builtin-help ()
  (interactive)
  (if helpful--callable-p
      (describe-function helpful--sym)
    (describe-variable helpful--sym)))
```
