### ISSUE TITLE
Fail to find all references of a function because of japan-util

### ISSUE THREAD

**Issue by akirak** [Wilfred/helpful#147]
I tried to find all references of a function using helpful but encountered the following error:

> Unexpected error whilst reading /usr/share/emacs/26.1/lisp/language/japan-util.el.gz position 1522: (invalid-read-syntax ?)

`japan-util.el` is encoded in `iso-2022-7bit`, and it seems to be why the command fails. Is there any workaround or fix to prevent this error?

**Comment by Wilfred** [comment]
References are handled by the `elisp-refs` package. Could you confirm you're on the latest version? This issue might be fixed by https://github.com/Wilfred/elisp-refs/commit/d0a63ae9e564f082c904c02fa5123f3a557886c6.

**Comment by akirak** [comment]
I have upgraded `elisp-refs` to the latest version (actually, the fix had been already applied), but it still produces the same error. Maybe there is something wrong with my system encoding?

**Comment by Wilfred** [comment]
Thanks for confirming.

OK, position 1522 is the first non-ASCII character in japan-util:

```
(defconst japanese-kana-table
  '((?あ
```

Could you please try the following:

1. I'd like to know what encoding Emacs is choosing. Open the file and view its encoding: `C-x C-f /usr/share/emacs/26.1/lisp/language/japan-util.el.gz RET C-: buffer-file-coding-system`

2. What's the value of `file-coding-system-alist`? You can see it with `M-x ielm RET file-coding-system-alist RET`.

**Comment by akirak** [comment]
Thank you for your advice. Apparently, my Emacs does not decode the file, which is encoded in `iso-2022-7bit`.

> I'd like to know what encoding Emacs is choosing. Open the file and view its encoding: C-x C-f /usr/share/emacs/26.1/lisp/language/japan-util.el.gz RET C-: buffer-file-coding-system

`utf-8-unix`

> What's the value of file-coding-system-alist? You can see it with M-x ielm RET file-coding-system-alist RET.

Most of the coding systems seem to be `no-conversion` : 

```
(("\\.tzst\\'" no-conversion . no-conversion)
 ("\\.zst\\'" no-conversion . no-conversion)
 ("\\.dz\\'" no-conversion . no-conversion)
 ("\\.txz\\'" no-conversion . no-conversion)
 ("\\.xz\\'" no-conversion . no-conversion)
 ("\\.lzma\\'" no-conversion . no-conversion)
 ("\\.lz\\'" no-conversion . no-conversion)
 ("\\.g?z\\'" no-conversion . no-conversion)
 ("\\.\\(?:tgz\\|svgz\\|sifz\\)\\'" no-conversion . no-conversion)
 ("\\.tbz2?\\'" no-conversion . no-conversion)
 ("\\.bz2\\'" no-conversion . no-conversion)
 ("\\.Z\\'" no-conversion . no-conversion)
 ("\\.elc\\'" . utf-8-emacs)
 ("\\.el\\'" . prefer-utf-8)
 ("\\.utf\\(-8\\)?\\'" . utf-8)
 ("\\.xml\\'" . xml-find-file-coding-system)
 ("\\(\\`\\|/\\)loaddefs.el\\'" raw-text . raw-text-unix)
 ("\\.tar\\'" no-conversion . no-conversion)
 ("\\.po[tx]?\\'\\|\\.po\\." . po-find-file-coding-system)
 ("\\.\\(tex\\|ltx\\|dtx\\|drv\\)\\'" . latexenc-find-file-coding-system)
 ("" undecided))
```

**Comment by Wilfred** [comment]
Hm, that's the same value of `file-coding-system-alist` that I have. What Emacs version are you using, and on what operating system?

**Comment by akirak** [comment]
I am using Manjaro Linux (or Arch Linux) and Emacs 26.1 from its official repository.

> 4.14.65-1-MANJARO #1 SMP PREEMPT Sat Aug 18 13:29:56 UTC 2018 x86_64 GNU/Linux

> GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

**Comment by Wilfred** [comment]
That's almost identical to my usual environment! (Arch Linux, Emacs 26.1)

Could you try `C-x C-f /usr/share/emacs/26.1/lisp/language/japan-util.el.gz RET C-: buffer-file-coding-system` from `emacs -Q`? I'd like to confirm whether it's something in your personal configuration.

**Comment by akirak** [comment]
The result of `buffer-file-coding-system` is `iso-2022-7bit-unix` on `emacs -Q`, while it is `utf8-unix` with my custom init.el. Apparently, it was due to my configuration, and after I removed `(setq-default coding-system-for-read 'utf-8)` from my config, helpful was able to find all references to a function. Thank you very much for your help!

**Comment by Wilfred** [comment]
Glad you found it :). I've updated elisp-refs to be more defensive.
