### ISSUE TITLE
Idea: add profiling / benchmarking buttons

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#151]
Helpful is a great entrypoint into Edebug and tracing. What about adding buttons for profiling and benchmarking too?

Say you add a button that says "Benchmark". When you click the button, you're prompted for a specific function call to run and perhaps a number of times to run it, and then it runs that function call that many times under profiling / benchmarking. This way, you don't have to worry about the details of benchmarking or profiling functions.

**Comment by Wilfred** [comment]
I don't think Helpful can add anything to the profiling workflow here. All we know is the name of the function: you still need to provide any required arguments and the number of times. It's not saving the user any work AFAICS.

**Comment by nickdrozd** [comment]
Users can be divided into two groups: those who are aware of the existence of Emacs profiling / benchmarking and those who are not.

For users in the second group, this would be a great discovery feature. I learned about both Edebug and the tracer from using Helpful, and exposing profiling and benchmarking could also lead people to use them who otherwise wouldn't.

For users in the first group, this could save some mental overhead as regards calling conventions as well as some boilerplate. Take the profiler for instance:

```emacs-lisp
(profiler-start TYPE) ;; 'cpu / 'mem
(dotimes (_ COUNT)
  (FUNCTION ARG1 ARG2))
(profiler-report)
(profiler-stop)
```

Stuff in caps needs to be supplied by the user, the rest is boring details.

I don't know exactly how it would work, but I'm pretty sure there's something worthwhile to add here. Are you open to a PR?

**Comment by Wilfred** [comment]
I'm not really sure that this is a good fit for helpful. I'm certainly open to discussing a PR, but I don't want you feel like I've wasted your time if I say no.

**Comment by nickdrozd** [comment]
Fair enough :)
