### ISSUE TITLE
Create buffer with helpful-mode

### ISSUE THREAD

**Issue by spatz** [Wilfred/helpful#16]
Currently the buffer is created and only afterwards `helpful-mode` is activated. This makes it impossible to use [popwin](https://github.com/m2ym/popwin-el) with helpful.

**Comment by Wilfred** [comment]
I don't understand, could you expand or create a pull request? `get-buffer-create` doesn't let you create the major mode immediately, and `helpful--buffer` activates `helpful-mode` as soon it can.

**Comment by spatz** [comment]
I might be able to open a pull request next week, if I can figure out how to fix this.

When you use `get-buffer-create` the buffer is created with fundamental mode as explained [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Buffers.html):
>The major mode for a newly created buffer is set to Fundamental mode.

Only after it is created you set the major mode to `helpful-mode`.

I don't know how the built-in help or `magit` or similar modes to this, but their buffers are created with their major mode from the start. Maybe they use `auto-mode-alist`?

**Comment by Wilfred** [comment]
I believe #35 fixes this. Let me know if not.

**Comment by spatz** [comment]
It does. Thank you very much!
