### ISSUE TITLE
use `variable-at-point' and `function-called-at-point' from `help-fns' rather than `thing-at-point'

### ISSUE THREAD

**Issue by slippycheeze** [Wilfred/helpful#163]
The default help system uses a specialized form to locate the symbol nearest the cursor, which is somewhat smarter than just `thing-at-point', since it will look backward to the closest appropriate symbol.  

This would require slightly specializing the internal `helpful--read-symbol' mechanism, or having several, to read the different symbol spaces, but it would also be much more DWIM, and reduce surprise for people moving from the standard help facility.

**Comment by Wilfred** [comment]
Yep, agreed. I bumped into this again recently:

```
(defcustom org-clock-out-when-done t
  "When non-nil, clock will be stopped when the clocked entry is marked DONE.
\\<org-mode-map>\
DONE here means any DONE-like state.
A nil value means clock will keep running until stopped explicitly with
`\\[org-clock-out]', or until the clock is started in a different item.
Instead of t, this can also be a list of TODO states that should trigger
clocking out."
  :group 'org-clock
  :type '(choice
	  (const :tag "No" nil)
	  (const :tag "Yes, when done" t)
	  (repeat :tag "State list"
		  (string :tag "TODO keyword"))))
```

When point is inside this form, it's much nicer if `helpful-variable` offers the symbol defined around point.
