### ISSUE TITLE
Superfluous puncuation not removed

### ISSUE THREAD

**Issue by pmarinov** [Wilfred/helpful#17]
_Helpful_ looks very nice.

I've noticed a problem. In the screenshots and in the description it states that: _We solve the text-quoting-style debate by removing superfluous puncuation entirely._

But I see it is still there when I invoke it. If via `M-x helpful-command` + `query-replace-regexp`, you look at one example paragraph:

_If ‘replace-regexp-lax-whitespace’ is non-nil, a space or spaces in the regexp
to be replaced will match a sequence of whitespace chars defined by the
regexp in ‘search-whitespace-regexp’._

Was this expected to be highlighted and not quoted?

**Comment by Wilfred** [comment]
This should now be fixed, do let me know.
