### ISSUE TITLE
Problem on using read to convert string to symbol?

### ISSUE THREAD

**Issue by xuchunyang** [Wilfred/helpful#172]
https://github.com/Wilfred/helpful/blob/039345ef60b4722d050c94ab1978540137df35f9/helpful.el#L2210

It doesn't work for such a valid function name.

```
(defun hello\ world ()
  '"hello world")

(read "hello world")
;; => hello

(intern "hello world")
;; => hello\ world
```

According to my experiments, It seems `read` works like `intern` (not `intern-soft` or `make-symbol`), thus `intern` should be used, but considering that at the above code context the symbol is already known by Emacs 100%, so `intern-soft` is more accurate?

**Comment by Wilfred** [comment]
I don't understand this I'm afraid. Could you give an example of where this causes a problem?

`read` does do the right thing with escaped spaces in symbols:

```
ELISP> (defun wh\ foo () 123)
wh\ foo
ELISP> (read "wh\\ foo")
wh\ foo
ELISP> (funcall (read "wh\\ foo"))
123 (#o173, #x7b, ?\{)
```

**Comment by xuchunyang** [comment]
To reproduce the issue, use `M-x helpful-function` to lookup `wh foo`.

In you code, `read` will receive `"wh foo"`, not `"wh\\ foo"`.
