### ISSUE TITLE
Can you make this a library / support Clojure/CIDER documentation?

### ISSUE THREAD

**Issue by ahungry** [Wilfred/helpful#182]
I really love this mode, so much so that going back to basic help buffers is very disappointing.

Have you ever considered making the view component receive a map of data or supporting other tools help buffers?

**Comment by Wilfred** [comment]
I think Helpful is pretty tightly coupled to elisp. There's not much display logic, it's mostly logic to find out data about the elisp symbol you're interested in.

I hope Cider can steal ideas, but it is already an impressive and featureful package. I suspect many of the Helpful features already exist in Cider in some form.

I don't see a useful way of doing this I'm afraid.
