### ISSUE TITLE
`find-function-C-source-directory` can be `nil`

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Wilfred/helpful#185]
`find-function-C-source-directory` can be `nil`:

```
find-function-C-source-directory is a variable defined in
find-func.el.gz.

Value
nil
```

and it should not result in error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "/home/user/")
  f-expand(nil "/home/user/")
  f-parent(nil)
  helpful--library-path("src/lread.c")
  helpful--definition(load t)
  helpful-update()
  helpful-callable(load)
```

protect that `f-parent` call accordingly (with `when find-function-C-source-directory`):

https://github.com/Wilfred/helpful/blob/2c6576f731282209492ca7c0217346deb9666785/helpful.el#L1178

**Comment by Wilfred** [comment]
I can't reproduce this. Could you give a full traceback?

Inside ielm, this seems to work as expected:

```
ELISP> find-function-C-source-directory
nil
ELISP> (helpful-callable 'load)
nil
```

`helpful-callable` shouldn't call `helpful--definition` if `find-function-C-source-directory` is `nil`.

**Comment by Alexander-Shukaev** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "/.../")
  f-expand(nil "/.../")
  f-parent(nil)
  helpful--library-path("src/fns.c")
  helpful--definition(require t)
  helpful-update()
  helpful-callable(require)
```

**Comment by Alexander-Shukaev** [comment]
That's the same traceback I already provided before.  Anything else you're looking for?

**Comment by Wilfred** [comment]
Weird, I still can't reproduce. To ask a silly question: are you sure you're using the latest version of helpful?

The source code of `helpful-update` looks like this:

```
;; snipped from -let*
(primitive-p (helpful--primitive-p helpful--sym helpful--callable-p))
(canonical-sym (helpful--canonical-symbol helpful--sym helpful--callable-p))
(look-for-src (or (not primitive-p)
                  find-function-C-source-directory))
((buf pos opened)
 (if look-for-src
     (helpful--definition helpful--sym helpful--callable-p)
   '(nil nil nil)))
```

So this should result in `look-for-src` being nil, and not calling `helpful--definition`.

What's the output of the following for you?

```
M-x ielm
(helpful--primitive-p 'load t)
```
```

**Comment by Alexander-Shukaev** [comment]
```
ELISP> (helpful--primitive-p 'load t)
*** Eval error ***  Symbol’s function definition is void: helpful--primitive-p
```

**Comment by Alexander-Shukaev** [comment]
```
;;; helpful.el --- a better *help* buffer            -*- lexical-binding: t; -*-

;; Copyright (C) 2017-2018  Wilfred Hughes

;; Author: Wilfred Hughes <me@wilfred.me.uk>
;; URL: https://github.com/Wilfred/helpful
;; Package-Version: 20190216.1818
;; Keywords: help, lisp
;; Version: 0.16
;; Package-Requires: ((emacs "25.1") (dash "2.12.0") (dash-functional "1.2.0") (s "1.11.0") (f "0.20.0") (elisp-refs "1.2") (shut-up "0.3"))
```

**Comment by CeleritasCelery** [comment]
Odd, I can't seem to reproduce this anymore either (using the latest helpful). `find-function-C-source-directory` is still nil, but it seems to handle it alright. Not sure what has changed.

**Comment by CeleritasCelery** [comment]
I don't see this issue with `load`. But I do see it with `rename-buffer`. When I call `(helpful--primitive-p 'rename-buffer t)` it returns nil. and therefore I hit the case where `find-function-C-source-directory` is nil.

**Comment by Alexander-Shukaev** [comment]
How is it even possible that you don't have an issue with `load` but have it with `rename-buffer`?

**Comment by CeleritasCelery** [comment]
The odd thing in my case is that `rename-buffer` is a lisp function, but Emacs thinks it is in `src/buffers.c` which is a C source file. 

@Alexander-Shukaev You need to require helpful before you can call `(helpful--primitive-p 'load t)`

**Comment by Alexander-Shukaev** [comment]
```
ELISP> (require 'helpful)
helpful
ELISP> (helpful--primitive-p 'load t)
nil
ELISP> (helpful--primitive-p 'require t)
nil
ELISP> (helpful--primitive-p 'rename-buffer t)
t
```

At the same time, `rename-buffer` works for me, it just says:

```
rename-buffer is an interactive function defined in C source code.

Signature
(rename-buffer NEWNAME &optional UNIQUE)
```

and both `load` and `require` signal error.

**Comment by CeleritasCelery** [comment]
I didn't realize `rename-buffer` was a C code function. So it looks like the issue happens when `helpful--primitive-p` returns nil for a c source function. That happens to you on `load` and `require` and happens to me on `rename-buffer`.

**Comment by CeleritasCelery** [comment]
what is the value of 
`(subrp (indirect-function 'load))`
and 
`(helpful--advised-p 'load)`

for you?

**Comment by Alexander-Shukaev** [comment]
```
ELISP> (require 'helpful)
helpful
ELISP> (subrp (indirect-function 'load))
nil
ELISP> (helpful--advised-p 'load)
t
```

**Comment by CeleritasCelery** [comment]
that is opposite for me. What advice do you have around `load`?

**Comment by Alexander-Shukaev** [comment]
```
load is a function without a source file.

Signature
(load FILE &optional NOERROR NOMESSAGE NOSUFFIX MUST-SUFFIX)

Documentation
:before advice: load@init-load/:before
:before advice: load@auto-compile
```

**Comment by CeleritasCelery** [comment]
I think I might have found the bug, can you try evaluating this and then calling helpful on one of your bad functions?
```elisp
(defun helpful--without-advice (sym)
  (advice--cd*r
   (advice--symbol-function sym)))
```

**Comment by Alexander-Shukaev** [comment]
Works now:

```
load is a function defined in C source code.

Signature
(load FILE &optional NOERROR NOMESSAGE NOSUFFIX MUST-SUFFIX)

Documentation
:before advice: load@init-load/:before
:before advice: load@auto-compile
```

**Comment by Wilfred** [comment]
Fabulous debugging, thanks for you help with this issue! I believe it's now fixed properly :)
