### ISSUE TITLE
`inhibit-read-only' does not update to the current value

### ISSUE THREAD

**Issue by ylluminarious** [Wilfred/helpful#189]
Whenever I try to get the current value for `inhibit-read-only` via `helpful-variable`, I always get the value `t` even when the actual value is `nil`. It does not matter what buffer I'm in. Whenever I refresh the buffer by pressing `g` (which calls `helpful-update`), the value still remains `t`. This has also persisted across Emacs sessions, so it is a reproducible bug for me at least. I can confirm that this is incorrect behavior because the same thing does not occur when I use `describe-variable`.

**Comment by Wilfred** [comment]
That's a subtle bug! Thanks :)

**Comment by ylluminarious** [comment]
@Wilfred Thanks a lot for fixing it!
