### ISSUE TITLE
Show variable name in helpful-variable

### ISSUE THREAD

**Issue by diamond-lizard** [Wilfred/helpful#19]
The helpful-variable function should show the name of the variable it's describing.

**Comment by Wilfred** [comment]
It's already mentioned in the mode line -- do you think it would be useful in the buffer too? If so, where?

**Comment by diamond-lizard** [comment]
Oh, I didn't even notice that.  I had gotten too used to seeing it displayed in the buffer when using describe-variable.

I think it would be useful, and the best place for it would be at the top of the buffer, just as describe-variable does it.  That's where my eyes most naturally go first, and usually it's the name and value of the variable which I most want to see.  The documentation and other info can come later.

By the way, maybe I should open a new issue for this, as this issue is just for the name of the variable, but it would be nice to see the value as well.

**Comment by Wilfred** [comment]
The value is now shown, see #15.

**Comment by diamond-lizard** [comment]
I see.  I think I must have had an older version of helpful which didn't show it.  Now that I updated to the newest version, I see the value.  Thank you.

I still think it would be most helpful at the top of the buffer, though, rather than buried somewhere down below.  The name and value are the most important things I look for when getting help on a variable.

**Comment by diamond-lizard** [comment]
Today I happened to look at the value of `auto-mode-alist` and saw that it was a gigantic list.  In this case, describe-variable prints the top of the help screen:
```
auto-mode-alist is a variable defined in `files.el'.
Its value is shown below.
```
I think that's a good approach for when the value of a variable can't be fit in to a line or two.  As a user, I'd still be looking at the top of the screen for the value, but then be redirected lower down the screen by what I read in the expected place.

**Comment by Wilfred** [comment]
I'm persuaded :). Fixed.
