### ISSUE TITLE
Can't handle (setf seq-elt)

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#190]
Did you know that `describe-function` will accept `(setf seq-elt)` as an input? Here's what it says:

```
\(setf\ seq-elt\) is a compiled Lisp function in ‘seq.el’.

(\(setf\ seq-elt\) ARG0 ARG &rest ARGS)

Not documented.

This is a generic function.

Implementations:

(store (sequence cons) n) in ‘seq.el’.

Undocumented

(store (sequence array) n) in ‘seq.el’.

Undocumented
```

Helpful fails for this one. I think it the error comes from `(get sym 'edebug)`, where `sym` is not actually a symbol.

I don't know how this should be handled. TBH I don't even fully understand what `(setf seq-elt)` means, despite the best efforts of @ebpa to explain it to me.

**Comment by nbfalcon** [comment]
@nickdrozd what version of Emacs are you running? The only issue I have with that function is the incorrect handling of the \= escapes, which I'll address in a PR soon.

**Comment by nickdrozd** [comment]
This works now.
