### ISSUE TITLE
helpful-function dead loop if looks for advice function esup

### ISSUE THREAD

**Issue by yygcode** [Wilfred/helpful#191]
I executed `helpful-function esup‘, waited for more than 10 seconds, and it didn't return. And I generate debug trace with debug-on-quit flag:
  1 Debugger entered--Lisp error: (quit)                                                                                                                       
  2   featurep(nadvice)                                                                                                                                        
  3   find-function-advised-original(esup)                                                                                                                     
  4   find-function-library(esup)                                                                                                                              
  5   helpful--definition(esup t)                                                                                                                              
  6   helpful-update()                                                                                                                                         
  7   helpful-function(esup)                                                                                                                                   
  8   funcall-interactively(helpful-function esup)                                                                                                             
  9   call-interactively(helpful-function record nil)                                                                                                          
 10   command-execute(helpful-function record)                                                                                                                 
 11   helm-M-x(nil #("helpful-function" 0 16 (match-part "helpful-function")))                                                                                 
 12   funcall-interactively(helm-M-x nil #("helpful-function" 0 16 (match-part "helpful-function")))                                                           
 13   call-interactively(helm-M-x nil nil)                                                                                                                     
 14   command-execute(helm-M-x) 

My relative config is:
```
  ;; When call esup function, esup would start a new emacs process
  ;; with option -L/-l to load esup, but until now init.el does not
  ;; loaded, so we need load init.el first.
  ;; Load if in esup.
  (unless (boundp 'user-init-config)
    (let ((file (expand-file-name "init.el" user-emacs-directory)))
      (message "y/esup: Esup profiling, load %s now" file)
      (load-file file)))

  (use-package esup
    ;; :quelpa (esup :fetcher github :repo "jschaf/esup" :stable nil)
    :pin melpa
    :init
    ;; Current version only support 1, see bug
    ;; https://github.com/jschaf/esup/issues/53
    (setq esup-depth 1)
    (setq esup-user-init-file
          (expand-file-name (concat (file-name-base user-init-config) ".el")
                            user-emacs-directory)))

  (defun y/esup-advice-before(&optional init-file)
    "Set env EMACS_Y_INTERNAL_ESUP_PROFILER."
    (setenv "EMACS_Y_INTERNAL_ESUP_PROFILER" "y/esup"))

  (defun y/esup-advice-after(&optional init-file)
    "Clear env EMACS_Y_INTERNAL_ESUP_PROFILER."
    (setenv "EMACS_Y_INTERNAL_ESUP_PROFILER" nil)
    t)
  ;; set env before esup, and clear env after esup
  ;; because we esup config.el but we need load init.el too.
  ;;          (add-function :override completing-read-function
  ;;                        #'helm--completing-read-default)
  (advice-add 'esup :before #'y/esup-advice-before)
  (advice-add 'esup :after #'y/esup-advice-after)
```

Then I tried execute elisp snippet `find-function-library('esup)', The function enter dead loop again. I thought its a common problem, then write a small function test it. The forward-char works error and forward-sentence works correctly:

forward-char:
elisp-refs--read-all-buffer-forms: Unexpected error whilst reading /home/yanyg/gnu/emacs-26.1.91/src/cmds.c position 756: (invalid-read-syntax #)Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")
Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")

forward-sentence:
Correctly.

Follow snippet is test code:
```
(defun y/esup-advice-before(&optional init-file)
  "Set env EMACS_Y_INTERNAL_ESUP_PROFILER."
  (setenv "EMACS_Y_INTERNAL_ESUP_PROFILER" "y/esup"))

(defun y/esup-advice-after(&optional init-file)
  "Clear env EMACS_Y_INTERNAL_ESUP_PROFILER."
  (setenv "EMACS_Y_INTERNAL_ESUP_PROFILER" nil))
;; set env before esup, and clear env after esup
;; because we esup config.el but we need load init.el too.
;;          (add-function :override completing-read-function
;;                        #'helm--completing-read-default)
(advice-add 'forward-char :before #'y/esup-advice-before)
(advice-add 'forward-char :after #'y/esup-advice-after)
(advice-add 'forward-sentence :before #'y/esup-advice-before)
(advice-add 'forward-sentence :after #'y/esup-advice-after)
```

**Comment by galeo** [comment]
+1 

I think I've met the same problem.

**Comment by Wilfred** [comment]
It looks like `helpful--ensure-loaded` is not autoloaded advised functions.
