### ISSUE TITLE
Prefer verbatim representation of a value

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Wilfred/helpful#200]
Follow up of #197.

Given `counsel`:

```emacs-lisp
(defcustom counsel-find-file-ignore-regexp nil
  "A regexp of files to ignore while in `counsel-find-file'.
These files are un-ignored if `ivy-text' matches them.  The
common way to show all files is to start `ivy-text' with a dot.
```

Output of `helpful`:

```
counsel-find-file-ignore-regexp is a variable defined in counsel.el.

Value
\(?:\`[#.]\)\|\(?:[#~]\'\)
```

Output of `help`:

```
counsel-find-file-ignore-regexp is a variable defined in ‘counsel.el’.
Its value is "\\(?:\\`[#.]\\)\\|\\(?:[#~]\\'\\)"
```

In my opinion, ``"\\(?:\\`[#.]\\)\\|\\(?:[#~]\\'\\)"`` is definitely better than ``\(?:\`[#.]\)\|\(?:[#~]\'\)`` because it can also be copied/pasted directly into Emacs Lisp and gives clear verbatim representation of the value.

**Comment by Wilfred** [comment]
This is already possible: try pressing the `View as literal` button.

Are you seeing the literal view or the pretty view on first load? For strings, we probably want the literal view as default.

**Comment by Alexander-Shukaev** [comment]
You are right, literal view looks very well but it's not the default one (for strings).
