### ISSUE TITLE
Keymaps with keyboard macros cause errors with helpful-variable

### ISSUE THREAD

**Issue by yuhan0** [Wilfred/helpful#202]
### Steps to reproduce:
- Evaluate the following
```elisp
(setq my-keymap (make-sparse-keymap))
(define-key my-keymap "a" "ABC")
```
- `M-x helpful-variable my-keymap`

### Expected behavior:
Pretty-printed representation of keymap in a `helpful` buffer

### Observed behavior:
Throws an error 
> Wrong type argument: listp, "ABC"

The same happens with key sequence vectors as macros:
```elisp
(define-key my-keymap "b" [tab])
```
> Wrong type argument: listp, [tab]

The stacktrace points to https://github.com/Wilfred/helpful/blob/master/helpful.el#L845 - there should probably be some sort of `(stringp keymap)` or `(vectorp keymap)` condition before that.

**Comment by Wilfred** [comment]
Aha, looks like bb41e5dd9141388338df1508675da89e60d029fc handles keyboard macros as functions, but not when they occur in keymaps.

**Comment by Wilfred** [comment]
Thanks, this should now be fixed.
