### ISSUE TITLE
Strange sort order with Helm

### ISSUE THREAD

**Issue by Ambrevar** [Wilfred/helpful#204]
Using Helm, helpful gives me a different sort order than with the original `describe-*` commands.

For instance

- M-x describe-variable RET "buffer file name"

returns `buffer-file-name` first and the matches are sorted following some logic.

- M-x helpful-variable RET "buffer file name"

there, `buffer-file-name` shows up in 5th position and the order seems completely random.

@thierryvolpiatto, any idea?

**Comment by Wilfred** [comment]
Can you reproduce this without helm?

**Comment by Ambrevar** [comment]
Well the problem can only be exhibited with Helm (or Ivy maybe, dunno),
because `buffer file name` (with spaces) can only be entered with Helm,
not with the default Emacs prompt.

Are you thinking of something else?

**Comment by bymoz089** [comment]
@Ambrevar This is something related to your helm setup.

I use ivy and with both commands your above steps `buffer-file-name` show up at second position. 
Check if you have something like `smex`, `prescient` or something else, which sorts the results, installed and active.

@Wilfred maybe this issue should be closed, because it's imo nothing related to helpful.

**Comment by Ambrevar** [comment]
No, I don't have anything like that.
I'll retest with with a minimal configuration and report back.

**Comment by Ambrevar** [comment]
I can reproduce the original recipe on an empty config.

@thierryvolpiatto: Which variables are these?  I cannot find them with my current config.

Emacs 26.3
Helm 3.3
Helpful 0.17

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I can reproduce the original recipe on an empty config.
>
> @thierryvolpiatto: Which variables are these? I cannot find them with my current config.

Checkout last helm from git or Melpa<not_stable>.

> Emacs 26.3
> Helm 3.3
> Helpful 0.17
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
So this only works with helm-apropos?

Any idea why the helpful-callable list is not ordered properly? (See
original post for an example.)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> So this only works with helm-apropos?

No, all commands that use describe-<something> e.g. helm-M-x.

> Any idea why the helpful-callable list is not ordered properly? (See
> original post for an example.)

Don't think it is a sort problem, just the lists provided by one and the
other are not exactly the same?

Also it depends of fuzzy matching enabled or not (the sort function
maybe different).
But, as long as you use helm-apropos and you are happy with it, why do
you bother of the generic functions behavior?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Works for me, thanks!
