### ISSUE TITLE
Is helpful--char-table-keys really used?

### ISSUE THREAD

**Issue by xuchunyang** [Wilfred/helpful#210]
I'm looking for something code example of `map-char-table`, and find

https://github.com/Wilfred/helpful/blob/897feba75ded5c93dcfc3d950319cf19c03252db/helpful.el#L819-L828

I wrote the similar and the code doesn't work

```el
(helpful--char-table-keys printable-chars)
;; => (([(4194176 . 4194303)] t) ([(4194176 . 4194303)] t))
``` 

versus

```el
(let (result)
  (map-char-table
   (lambda (range value)
     (push (list (format "%S" range) value) result))
   printable-chars)
  result)
;; => (("(160 . 4194175)" t) ("(32 . 126)" t))
```

It seems the `range` is "shared" across the function calls.

Anyway, it seems `helpful--char-table-keys` is never used, if it's true, it should be removed.

**Comment by Wilfred** [comment]
Thanks, you're right it's not used.

FWIW there is a correct example of `map-char-table` in helpful.el:

https://github.com/Wilfred/helpful/blob/8ac851e7c0f8345046d053d136befe28fd75dcd9/helpful.el#L856-L864
