### ISSUE TITLE
A simple way to make helpful work with "counsel-M-x"

### ISSUE THREAD

**Issue by mrbig033** [Wilfred/helpful#218]
[The recommendation on the readme](https://github.com/Wilfred/helpful#usage) was not enough, because it did nothing about the `help` on the `ivy-set-actions` that are available by hitting `counsel-M-x` followed by `M-o`. 

I had to configure `ivy-set-actions` itself, which was not that hard after reading the source code. 

Here's the solution:

``` emacs-lisp
(use-package ivy
  :ensure t
  :config

  (setq counsel-describe-function-function #'helpful-callable)
  (setq counsel-describe-variable-function #'helpful-variable)

  (ivy-set-actions
   'counsel-M-x
   `(("d" counsel--find-symbol "definition")
     ("h" ,(lambda (x) (helpful-callable (intern x))) "help"))))
```

**Comment by Wilfred** [comment]
Fixed upstream.
