### ISSUE TITLE
Keep the same window configuration as original help function

### ISSUE THREAD

**Issue by narendraj9** [Wilfred/helpful#22]
Currently, the helpful help function cause the whole window to be occupied by the helpful-mode buffer which isn't the case with original help functions.

**Comment by Wilfred** [comment]
Strictly speaking, the original functions do sometimes change the window configuration. If you only have one buffer visible, it will split the frame.

Do you think the original functions' behaviour is better? Why? I don't feel strongly, but I feel like we should have a good reason for whatever behaviour we choose.

**Comment by narendraj9** [comment]
I, personally, like having the *Help* buffer open up on the side so that I am still able to see the code I was interested in and the help lookup doesn't become the central thing. This simply signifies that the context is there (for me).    I am not sure if this reason is sufficient to change this for everyone. 

Moreover, I would really like if the helpful commands also showed the current value of the variable as the original help functions.

**Comment by Wilfred** [comment]
Fixed in #35.
