### ISSUE TITLE
Question about helpful--start-buffer

### ISSUE THREAD

**Issue by casouri** [Wilfred/helpful#227]
I'm using helpful as a backend and sometimes I can't provide a `helpful--start-buffer` for it. Will nil-valued `helpful--start-buffer` and `helpful--associated-buffer` cause any problem? Thanks.

**Comment by Wilfred** [comment]
That's absolutely fine :)

`helpful--start-buffer` is just used for the default value when prompting the user for a buffer.

`helpful--associated-buffer` is used when viewing the buffer-local value of a variable.

They're `nil` by default anyway. You shouldn't need to use private `helpful--foo` variables, so I'm interested to hear if you have any cases of variables that should be public `helpful-foo`.

**Comment by casouri** [comment]
Thanks. I'm using my [ghelp](https://github.com/casouri/ghelp) and I wrote a helpful backend for it. So there is no need to make them public for normal use cases.
