### ISSUE TITLE
helpful-at-point blows up if not pointing to a defined thing (see #221)

### ISSUE THREAD

**Issue by zenspider** [Wilfred/helpful#238]
Closing an issue (#221) when you didn't even try the described problem and then not re-opening it when it is demonstrated that it is still an issue is frustrating. So, I'm filing this to make sure SOMETHING is open.

**Comment by Wilfred** [comment]
Sorry about that. I did try to replicate initially (hence the ielm session) but I haven't had time to investigate further yet.

I'm very happy for you to reopen issues when you provide repro steps, by the way :)

#221 is open, so I'm closing this. If you think my approach to issues needs documenting better, feel free to reopen and discuss this too.
