### ISSUE TITLE
[info] gccemacs support

### ISSUE THREAD

**Issue by sebastiansturm** [Wilfred/helpful#239]
This is not an important issue, just wanted to let you know:

when using the new `nativecomp` branch of Emacs (specifically, I tried it with commit 65cc8efa), `describe-function` reports natively compiled functions as `native compiled Lisp function`, but helpful (which doom uses as a drop-in replacement for `describe-function`) doesn't. Maybe I'll do a PR at some point but now that I know about the issue, it doesn't really bother me much.

**Comment by hlissner** [comment]
This was resolved in #240, so this can be closed.
