### ISSUE TITLE
helpful-command can't find use-package while helpful-macro can

### ISSUE THREAD

**Issue by spatz** [Wilfred/helpful#26]
The 3 functions behave differently:

1. `helpful-function` shows many function containing the string "use-package" but not the macro itself
1. `helpful-macro` only shows the `use-package` macro
1. `helpful-command` shows only `use-package-install-deferred-package` and `use-package-jump-to-package-form`

**Comment by spatz** [comment]
Trying to find the differences I think this might be related to `use-package` being autoloaded, so this might be a duplicate of #23. If so then I'm sorry for spamming.

**Comment by Wilfred** [comment]
This seems correct to me.

`use-package` is a macro, so I would only expect it to be offered by `helpful-macro` or `helpful-callable`.

**Comment by spatz** [comment]
Whoops, you're right. I got confused between `helpful-command` and `helpful-callable` for some reason.
Sorry for the noise.
