### ISSUE TITLE
helpful-function does not show that a function is an alias

### ISSUE THREAD

**Issue by DamienCassou** [Wilfred/helpful#27]
When using `helpful-function` the buffer does not show that the function is an alias of another one. For example `M-x helpful-function RET yes-or-no-p RET` does not say that it is an alias of `y-or-n-p`. I only saw a message in the echo area.

**Comment by Wilfred** [comment]
OK, this confused me slightly. `yes-or-no-p` isn't an alias for `y-or-n-p` unless you have the following in your configuration:

```emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
```

Turns out that I have this config too :)
