### ISSUE TITLE
```Invalid function: 2``` in `helpful--format-properties'

### ISSUE THREAD

**Issue by c1-g** [Wilfred/helpful#276]
The problem lies in the `-partition` form. The code was added long ago so I'm not sure if I'm the only one getting this error.
If you want a backtrace let me know.

**Comment by Wilfred** [comment]
Yeah, a backtrace and if possible a repro would be super helpful :)

**Comment by c1-g** [comment]
Nevermind! This error is caused by another package overriding dash's `-partition` I submitted the patch to it and resolved it.
