### ISSUE TITLE
Minor modes for editing slow down Helpful startup

### ISSUE THREAD

**Issue by kisaragi-hiu** [Wilfred/helpful#287]
Context: I'm (still) using parinfer-mode, which is quite slow for large files. When looking up definitions in large files like org.el or flycheck.el, the slow minor mode ends up being run even though it is irrelevent for Helpful. This applies to any slow functions that are only for editing.

It would be ideal if we could somehow know a minor mode is for editing and does not need to be run when Helpful opens a file to read the definition of a symbol. This is, however, kind of impossible.

Another option might be to locally set `emacs-lisp-mode-hook` to nil in `helpful--definition`, but this also makes it impossible to run emacs lisp-specific highlighting minor modes (like lisp-extra-font-lock-mode) and have them show up in Helpful.

Yet another option would be to add a user option containing functions to remove from emacs-lisp-mode-hook when Helpful reads the file, but I'm not sure which is the best approach.

**Comment by shouya** [comment]
I second this. I also suffer from the slow loading problem with Helpful for a long time. Thanks to your issue I found that the culprit is indeed parinfer.

It would also possible for Helpful to set a local variable to the buffer when it reads a file, so I can avoid loading parinfer-mode based on that variable.

**Comment by Wilfred** [comment]
I think this should be better now, let me know how it goes.

**Comment by kisaragi-hiu** [comment]
It's indeed better now, thank you so much!

However, currently `(helpful-callable 'org-mode)` errors because [an unbalanced close paren in a comment](https://github.com/bzg/org-mode/blob/main/lisp/org.el#L4815-L4816) trips up `narrow-to-defun` in [helpful--source](https://github.com/Wilfred/helpful/blob/db1e15b3783c83d9781a546f37b900ad53576659/helpful.el#L1226). `parse-sexp-ignore-comments` would have to be t when that `narrow-to-defun` runs.
