### ISSUE TITLE
Eev now supports helpful

### ISSUE THREAD

**Issue by edrx** [Wilfred/helpful#288]
Hi Wilfred,

so: now eev has support for helpful! If a person has both eev and helpful and she types `M-h M-h` or `M-x find-here-links` in a helpful buffer then `find-here-links` detects that "here" is a buffer in helpful-mode, and `find-here-links` produces a temporary buffer containing refinable sexp hyperlinks to that helpful buffer... see:

http://angg.twu.net/eev-intros/find-eev-quick-intro.html#3
http://angg.twu.net/eev-intros/find-here-links-intro.html#2
http://angg.twu.net/eev-intros/find-refining-intro.html#2

Cheers! =)
  Eduardo Ochs
  http://angg.twu.net/#eev

**Comment by Wilfred** [comment]
Nice! :)
