### ISSUE TITLE
Question: using ido with helpful-*

### ISSUE THREAD

**Issue by mmahmoudian** [Wilfred/helpful#298]
I just found this package and as a new/n00b emacs user I really appreciate the way Helpful simplifies and color codes the help section AND pulling down the source code and display it. Thank you for the great package.

In the README you have briefly touched upon Ivy, but I was wondering if there is an easy/intuitive way to use this with ido?

**Comment by minad** [comment]
You can use https://github.com/DarwinAwardWinner/ido-completing-read-plus. But I recommend to move away from Ido to completion UI which has been designed to handle all completion contexts out of the box (Helm, Icomplete, Ivy, Vertico).
