### ISSUE TITLE
Find all references not working on latest emacs29 build from git

### ISSUE THREAD

**Issue by dinkonin** [Wilfred/helpful#306]
When I run Find all references on a freshly built emacs from git I always endup with 0 results
`Found 0 references to function [function/variable/macro]. Searched all 180
files loaded in Emacs.`

I tested with ` emacs -Q -l test.el` with the following contents:
```elisp
(add-to-list 'load-path "PATHTO/helpful")
(add-to-list 'load-path "PATHTO/elisp-refs/")
(add-to-list 'load-path "PATHTO/dash.el/")
(add-to-list 'load-path "PATHTO/s.el/")
(add-to-list 'load-path "PATHTO/f.el/")

(require 'helpful)
```
emacs-version returns: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-11-09`

**Comment by zenspider** [comment]
Confirmed w/ packaged version of 29.1

All reference searches come back 0:

```
Found 0 references to function comint-osc-process-output. Searched all
394 files loaded in Emacs.
```

**Comment by zenspider** [comment]
I would suggest removing "build from git" from the title as that doesn't seem relevant

**Comment by dinkonin** [comment]
Oops I forgot about this issue, I think it's better to just close it as I no longer experience this on 29.3 and 30 on multple systems. Feel free to open a new one.
