### ISSUE TITLE
Add support for org links

### ISSUE THREAD

**Issue by dakra** [Wilfred/helpful#38]
Calling (org-store-link) in a normal buffer stores the link to the help buffer.
Would be nice if helpful would support this too.

**Comment by notuntoward** [comment]
I was looking for this too.

**Comment by Wilfred** [comment]
I'm not familiar with this behaviour, could you explain? Calling `org-store-link` on what, in what kind of normal buffer?

**Comment by dakra** [comment]
Sorry for the confusing writing.. With 'normal buffer' I meant the buffer that opens when you call the normal help function like `describe-variable`. In there (and almost anywhere in Emacs actually) you can call `org-store-link` that saves a reference to that buffer+location. Then in your org file you can paste the stored link with `org-insert-link`.

**Comment by codeluggage** [comment]
I came here looking for this too. Adding error message for posterity: 
```
user-error: No method for storing a link from this buffer 
```

**Comment by DamienCassou** [comment]
Can you please try PR #304?

**Comment by DamienCassou** [comment]
Has anyone tried this?

**Comment by yewton** [comment]
@DamienCassou It worked like a charm! Thank you!
