### ISSUE TITLE
`C-h k` burns CPU for unknown binding

### ISSUE THREAD

**Issue by DamienCassou** [Wilfred/helpful#41]
When using [borg-queen](https://github.com/thblt/borg-queen), and binding `C-h k` to `helpful-key`, `C-h k t` takes all my CPU and doesn't produce anything until I kill it with `C-g`. `M-x describe-key RET t` produces 

> Symbol’s function definition is void: borg-queen-mark-for-checkout-tag

which is correct as `t` is bound to an unknown command.

**Comment by Wilfred** [comment]
Sounds like a bug.

Out of interest, what happens when you press `t`? Binding a key to a nonexistent command seems like an odd thing to do.

**Comment by DamienCassou** [comment]
Wilfred Hughes <notifications@github.com> writes:
> Out of interest, what happens when you press `t`?


an error :-)


> Binding a key to a nonexistent command seems like an odd thing to do.


the package is pre-alpha quality with a lot of missing features :-).


-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by narendraj9** [comment]
Pull request to fix the above: https://github.com/Wilfred/helpful/pull/43

**Comment by Wilfred** [comment]
Fixed in #43.
