### ISSUE TITLE
Fails while parsing files with parenthesis in comments

### ISSUE THREAD

**Issue by narendraj9** [Wilfred/helpful#46]
`backward-up-list` isn't smart enough to see that an opening parenthesis is inside comments. That causes `helpful-function' to fail for functions like `org-macro--collect-macros' as the source file contains comments with open parenthesis in them. 

I am not sure how we can make sure that we stop moving up when we have reached the top-level as we cannot assume that a definition should always start at the zeroth column

**Comment by narendraj9** [comment]
https://github.com/Wilfred/helpful/pull/47 works for me most of the times.

**Comment by Wilfred** [comment]
I can't reproduce this. Running `helpful-function` on `org-macro--collect-macros` gives me a normal helpful buffer.

However, it's quite possible that my version of org-mode is different to yours. Could you point me at the exact source file you're looking at, or perhaps put it on gist.github.com?

We could also look at using `beginning-of-defun` but I suspect it may suffer from the same issue (the docstring mentions `open-paren-in-column-0-is-defun-start`.

**Comment by narendraj9** [comment]
Here is a link to my `org-macro.el` that causes this issue: https://gist.github.com/narendraj9/250e7d7bbf2bc07c420f79f0d679cfaa 

I am using
```GNU Emacs 27.0.50 (build 11, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-10-13````
```Org 9.1.2```

**Comment by Wilfred** [comment]
I'm still not managing to reproduce this. You mentioned that `helpful-function` is failing, how is it failing exactly?

![helpful_org_macro](https://user-images.githubusercontent.com/70800/31636400-3168f530-b2c2-11e7-9d55-28694917a788.png)

**Comment by Wilfred** [comment]
I've refactored the logic, could you try again please?

**Comment by narendraj9** [comment]
@Wilfred Thanks! :) I will try it today or tomorrow. BTW, what is this theme that you are using. It's pleasant :)

**Comment by Wilfred** [comment]
https://github.com/juba/color-theme-tangotango :)

**Comment by narendraj9** [comment]
@Wilfred It's fixed for me now! :) Thanks! :)
