### ISSUE TITLE
helpful-variable gets variable value too late

### ISSUE THREAD

**Issue by drrlvn** [Wilfred/helpful#50]
The value of the variable shown is taken too late after it has potentially already been changed by helpful.
The easiest way for me to explain this is with an example: using `describe-variable` on `major-mode` shows the major mode for the buffer, e.g. `lisp-interaction-mode` while using `helpful-variable` shows `helpful-mode`.

**Comment by Wilfred** [comment]
Thanks, should now be fixed.
