### ISSUE TITLE
helpful-variable crashes for variables defined on C-source

### ISSUE THREAD

**Issue by DamienCassou** [Wilfred/helpful#51]
Followup to #28. @Townk @Wilfred @dakra.

I can still reproduce the issue with `M-x helpful-variable RET shell-file-name`.

- Emacs version: 26.0.90, compiled from `emacs-26` branch
- `find-function-C-source-directory` is properly set
- `M-x describe-variable RET shell-file-name` works fine and I can click on the "C source code" link
- helpful is at latest commit from `master` branch

**Comment by narendraj9** [comment]
@DamienCassou I am facing the same issue.

**Comment by narendraj9** [comment]
The strange thing is that sometimes it works. I tried removing the byte-compiled file just to be sure that it's not doing anything weird with no luck.

**Comment by narendraj9** [comment]
@Wilfred @DamienCassou https://github.com/Wilfred/helpful/pull/53 fixes it for me.

**Comment by dakra** [comment]
#53 seems to fix it for me as well.

**Comment by Wilfred** [comment]
Merged #53 :)
