### ISSUE TITLE
"All references" links should jump to the reference

### ISSUE THREAD

**Issue by notuntoward** [Wilfred/helpful#57]
It would be an improvement if the links generated by "All references" jumped to the line of code where the reference is, something like how grep would behave.  In fact, I'd like the interface to behave something like emacs's grep, where there are keybindings that allow you to quickly hop between all the calling instances.

**Comment by Wilfred** [comment]
This is already the case, isn't it?

If you click `All References` in helpful buffer, you end up with a `*refs: foo*` buffer. In that buffer, you can press RET to visit the result at point, and `n` and `p` will move between results.

**Comment by notuntoward** [comment]
Oh, sorry, I didn't notice that option.  This does exactly what I wanted.  Thanks for that.
