### ISSUE TITLE
Screwed up formatting for new function

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/helpful#58]
`helpful-function` sometimes overwrites buffers with strange output. This seems to happen for functions that are newly-defined.

`GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21`

`helpful: 20171116.1425`

1. Start Emacs with `emacs -Q` and load `helpful` (in the process of doing this, I also load `use-package`).

2. Open a file called `~/bug-in-helpful.el`. Define and evaluate the following function:
```
(defun bug-in-helpful ()
  "a bug in helpful.el"
  5)
```
Save the file. The screen should look like this:

![helpful-1](https://user-images.githubusercontent.com/17630138/33437544-e7c2af3e-d5ad-11e7-840b-026e56e16b82.png)

3. Call `M-x helpful-function RET bug-in-helpful`. For me, this causes a new window to open with the same buffer (`bug-in-helpful.el`). In the buffer (and hence in both windows), the text has been replaced with `helpful-function` output which is missing most information (it only has the source code, and that is in the form of a lambda).

![helpful-2](https://user-images.githubusercontent.com/17630138/33437767-8e480570-d5ae-11e7-842b-3258bb709970.png)

Note that the buffer has been marked as having been changed.

4. Undo the buffer change and close the extra window. Then call `C-h f bug-in-helpful`. This displays without any problems:

![helpful-3](https://user-images.githubusercontent.com/17630138/33437856-d5179c9a-d5ae-11e7-850e-c29b0c251971.png)

5. Close the `help` window and repeat step 3. The strange behavior still occurs.

**Comment by Wilfred** [comment]
Aha, I think I've managed to reproduce this. It looks like it happens to functions that are defined interactively, where Emacs doesn't know the source file.
