### ISSUE TITLE
feature request: Make variable in helpful-variable buffer customizable

### ISSUE THREAD

**Issue by Dickby** [Wilfred/helpful#59]
the old `describe-variable` function has this `You can customize this variable.` part, if the variable is declared with `defcustom` with a link to the customization buffer.
It would be nice to have something similar in `helpful-variable`.
One suggestion for this (just my personal preference) is to make the value editable inside the helpful-buffer, a bit like `wdired` or `wgrep`.
Thanks for this great package.

**Comment by Wilfred** [comment]
OK, I've added toggle, set and customize buttons.

**Comment by Dickby** [comment]
Nice, Thanks!
