### ISSUE TITLE
Some info about usage would be nice, especially for newbies

### ISSUE THREAD

**Issue by dahanbn** [Wilfred/helpful#60]
Hi Wilfred,

great package and currently I am exploring the different functions helpful provide. 

As an Emacs newbie myself it's sometimes hard to look at the source to discover the functionality of a package. So it would be nice to get some info about that in the README. 

Especially stuff like how the different helpful functions could replace the builtins and how to do so in my emacs config file.

**Comment by dahanbn** [comment]
Just discovered helpful-callable as drop-in replacement for describe-function. I am wondering what I should at to my emacs config to configure it as replacement. Especially that it would be called with `C-h f` and also with at point functionality.

**Comment by dahanbn** [comment]
Thanks. That was quick. :-)

**Comment by Wilfred** [comment]
You're welcome :)
