### ISSUE TITLE
helpful-variable value

### ISSUE THREAD

**Issue by sjLambda** [Wilfred/helpful#64]
How come the helpful-variable does not show the current value of the variable as describe-variable does? Is there a valid reason that for this omission?

Also, I just checked M-x and found 57 other desribe-* commands. Of these fonts, encoding, minor-mode, fontsets, and other misc ones may be worthwhile for helpful-like presentation.

Lastly, many apropos-* commands may also benefit from helpful-* upgrades. apropos-value is my most used command. 

Thanks.

**Comment by Wilfred** [comment]
It should show the current value of the variable. What are you seeing?

#25 is tracking `helpful-apropos`. If there are other commands that you'd like to see in helpful, could you mention which and how you think they'd work in helpful?

**Comment by Wilfred** [comment]
Since we do show the current value, I don't think there's anything left to do here. Let me know if you see any issues.
