### ISSUE TITLE
Empty buffer with special forms

### ISSUE THREAD

**Issue by NicolasPetton** [Wilfred/helpful#65]
Calling `helpful-function` or `helpful-callable` on any special form (`setq`, `and`, etc.) yields an empty help buffer.

**Comment by NicolasPetton** [comment]
I'm using Emacs 26 (from the emacs-26 branch).
The error is `Can’t find library src/eval.c`.

`find-function-noselect` works fine though (it uses `find-function-search-for-symbol`, which seems to do the right thing).

**Comment by DamienCassou** [comment]
I have the same problem (using Emacs 26 and e4437e1135afdfcf87cee18e099e275d97318d17).

**Comment by Wilfred** [comment]
This is no longer crashing, but it's currently just showing 'subr' for the source code.

**Comment by Wilfred** [comment]
OK, I think this is now fixed. Let me know if you hit any issues.
