### ISSUE TITLE
Reuse buffer

### ISSUE THREAD

**Issue by technician77** [Wilfred/helpful#66]
I often used describe variable and describe key. For some reason the helpful couterparts open a new buffer for each request which their built-in counterparts do not.

Is there any way to make helpful use just one buffer for all outputs and recycle it for any new command?

I can understand there might be reasons to have it the way it is but a variable that would allow merging everything into one buffer would be great.

Kind regards,
tech77

**Comment by Wilfred** [comment]
The latest version, along with `(setq helpful-max-buffers 1)` should do what you want. :)
