### ISSUE TITLE
Couple suggestions regarding file names

### ISSUE THREAD

**Issue by dieggsy** [Wilfred/helpful#67]
It'd be nice to have a "basename" option for file names, like emacs' default help does. (that is, the link just displays `filename.el` or `filename.c`, and takes you to the appropriate location on click or `push-button`).

I think it's a bit unclear to say "No references found in" when the symbol is actually defined in that file but not referenced elsewhere within it. Maybe this could be divided into a line stating where the thing is defined and a separate references section.

**Comment by dieggsy** [comment]
Huh, I see there's already a separate "defined in" above the source code - in which case it might be useful to (additionally?) state this higher up in the helpful buffer.

**Comment by dieggsy** [comment]
I'll close this as I opened a PR for the first idea, and I'm kind of understanding the second is uneccessary. If I need to see the definition, I can jump to the end of the buffer. Otherwise, I can see where it's used in the references section.

**Comment by Wilfred** [comment]
I've tweaked the wording to say `helpful-at-point is unused in ~/projects/helpful/helpful.el.`. I think this is clearer -- would that have prevented your confusion?

I agree the problem before is that users might think References includes the definition, whereas we're looking for all references except the definition.

**Comment by dieggsy** [comment]
Sure, that's a bit better - I still think the statement of where the function is defined should be more visible or clearer, near the top maybe. This is cause with a really long docstring, refs list, symbol properties etc. It's not immediately apparent where the symbol is defined

**Comment by Wilfred** [comment]
Yep, helpful is trying to strike a good balance between being very informative without drowning you information.

Do you have an symbols that you think are particularly good examples of the symbol definition not being clear?

**Comment by dieggsy** [comment]
This seems solved now, closing.
