### ISSUE TITLE
propertized buffer-file-name cause recentf or saveplace failed to read saved history

### ISSUE THREAD

**Issue by deftsp** [Wilfred/helpful#68]
The helpful buffer make recentf save following item to recentf-save-file, but it can not be read back.
    #("/usr/local/Cellar/emacs-mac/HEAD-cd646b7/share/emacs/26.0.90/lisp/recentf.el.gz" 0 79 (button (t) category helpful-navigate-button-button path #0 position 2978))

**Comment by Wilfred** [comment]
Thanks. This *should* now be fixed, but let me know if not.

You will need to manually edit `recentf-list` in your local instance to fix your current list. You'll also need to edit the file `~/.recentf` to remove any propertized strings written then (they start with `#`).
