### ISSUE TITLE
Can't find functions defined in C code

### ISSUE THREAD

**Issue by mookid** [Wilfred/helpful#71]
HI @Wilfred  and thanks for this package!

When calling `helpful-at-point` on (for instance) `mapconcat`, I get the error `"Can’t find library src/fns.c"`, while `xref-find-definitions` finds its way to the source.

**Comment by Wilfred** [comment]
I think this is a duplicate of #65 -- please upgrade :)

**Comment by mookid** [comment]
confirmed, sorry for the noise!
