### ISSUE TITLE
unexpected error whilst reading .gz file

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [Wilfred/helpful#75]
I'm using emacs 25.1 on Debian 9. Lately `helpful` hasn't been working for me. Often when I look up functions (like `toggle-debug-on-error` for example I get errors like this: 
`"Unexpected error whilst reading %s position %s: %s" "/usr/share/emacs/25.1/lisp/menu-bar.el.gz" 146 (invalid-read-syntax "?"))`.
When I use `describe-function`, however, I get the correct output. 

I have a feeling that I did something to break helpful, because It was working fine a few days ago but I havent touched the `.gz` files in my emacs.

**Comment by Wilfred** [comment]
What version of elisp-refs do you have installed? I suspect you're on an old version.

**Comment by Luis-Henriquez-Perez** [comment]
I think I have the latest. I have the git repository installed. When I used `magit-status` on it I got this result.

    Head:     master Require a valid version of loop.el
    Merge:    origin/master Require a valid version of loop.el
    Tag:      1.2 (5)

    Recent commits
    ae5abe0 master origin/master Require a valid version of loop.el

**Comment by Wilfred** [comment]
What happens if you open menu-bar.el.gz and do `M-: (goto-char 146)`? What line of code is that?

**Comment by Luis-Henriquez-Perez** [comment]
That specific character is '\243' and the character after that is 'z'. It is line number 1. Im assuming this is the '?' the error refers to.

**Comment by Wilfred** [comment]
Weird, could you paste the full line of code? If I check out the Emacs source code at 25.1 and look at menu-bar.el, position 146 is on this line:

```
;; Author: Richard M. Stallman
```

which is really strange as it's just a comment. Presumably your menu-bar.el is different?

**Comment by Luis-Henriquez-Perez** [comment]
I looked at `menu-bar.el.gz` which is compressed which is why I think I didnt see the rms line. For some reason my browswer wont allow me to paste the line from `menu-bar.el.gz`. Maybe because its in binary? I can take a screenshot if that would help. I dont see a plain `menu-bar.el` file in my lisp directory.

**Comment by Wilfred** [comment]
Because I checked out the Emacs source code, I have menu-bar.el rather than menu-bar.el.gz. They should be the same.

A screenshot would definitely help :).

**Comment by Luis-Henriquez-Perez** [comment]
This screenshot is an overview of the `menu-bar.el.gz` file. 
![full-screen](https://user-images.githubusercontent.com/30783193/34133845-1467f26c-e425-11e7-8e41-a73966f436a3.png)

In this screenshot I specifically focused on line one. To the right you can see the `\243` and the `z`.
![screenshot_2017-12-18_18-55-31](https://user-images.githubusercontent.com/30783193/34133846-1b55dc60-e425-11e7-9dbd-77d3b8b528a4.png)

When I run `(goto-char 146)` the cursor takes me to the slash at `\243`.

**Comment by Wilfred** [comment]
Aha, OK. So the problem is that elisp-refs is looking at the raw binary data rather than the decompressed data. I wonder why.

**Comment by Luis-Henriquez-Perez** [comment]
Maybe its because there is no decompressed data in my lisp directory. I didnt find any decompressed version. Should there be?

**Comment by Luis-Henriquez-Perez** [comment]
I guess I will close this issue because it's a matter of adding the decompressed files to my lisp directory.

**Comment by Wilfred** [comment]
I disagree -- I think you've hit a legitimate bug :)

It's normal to have foo.el.gz files in Emacs -- all the elisp files Emacs ships with are compressed.

**Comment by Wilfred** [comment]
What's the value of `auto-compression-mode` in your Emacs?

**Comment by Luis-Henriquez-Perez** [comment]
Oh ok I'm happy I can contribute to helpful :). It's value is t.

**Comment by Luis-Henriquez-Perez** [comment]
So I used my morning today to debug this issue. I realized in my config had because when I started emacs with `emacs -q` and helpful worked fine. When I debugged my config I realized I had

 `(setq file-name-handler-alist nil)`

This is what caused the problem. I'll leave this open for a few hours in case you or anyone looking at this has any comments or questions.

**Comment by Wilfred** [comment]
Aha, great debugging! I've fixed `elisp-refs` to handle users modifying `file-name-handler-alist`. I can't see why you'd want to change it though -- what configuration did you copy that from, out of interest?

**Comment by Luis-Henriquez-Perez** [comment]
I copied it from [DOOM](https://github.com/hlissner/doom-emacs), specifically from [core.el](https://github.com/hlissner/doom-emacs/blob/master/core/core.el). Over the past few weeks I made (and am still making) a lot of changes to my own configuration mainly focused on fast startup time and literate programming. And I thought DOOM seemed like a useful model for the fast startup goal.
