### ISSUE TITLE
Drop-in replacement for C-h f <describe-function>?

### ISSUE THREAD

**Issue by DamienCassou** [Wilfred/helpful#8]
Would it be possible to provide a command that could be used instead of `C-h f` (`describe-function`)? The command would show a list of all functions in the system with a default for the function at point.

**Comment by Wilfred** [comment]
Does `helpful-function` meet your needs? The only difference here is that `helpful-function` only offers completion for functions, whereas `describe-function` does macro too.

**Comment by DamienCassou** [comment]
I will use that for a while and open issues if I have problems. Thanks.
