### ISSUE TITLE
Better formatting/rendering of description 

### ISSUE THREAD

**Issue by nixmaniack** [Wilfred/helpful#80]
The bottom buffer shows how `describe-function` renders while the top buffer shows how `helpful` is rendering. 

helpful
```
Thus, (apply \='+ 1 2 \='(3 4)) returns 10.
```
vs. help-mode
```
Thus, (apply '+ 1 2 '(3 4)) returns 10.
```
<img width="537" alt="screen shot 2017-12-28 at 12 33 16 am" src="https://user-images.githubusercontent.com/542810/34390644-165626d6-eb67-11e7-95d4-87bcbd0b5e92.png">

**Comment by Wilfred** [comment]
Thanks, that was a little fiddly. Fixed.
