### ISSUE TITLE
Can't find library

### ISSUE THREAD

**Issue by socketwiz** [Wilfred/helpful#88]
I'm using Emacs v25.3.2 on Ubuntu v16.04.3 with helpful v20180102.1528 and I'm getting the following error when I try to use `helpful-key` in `org-mode`:

Can't find library /usr/share/emacs/25.3/lisp/org/org

I've confirmed the directory structure exists up to /usr/share/emacs/25.3/lisp/org and it has a bunch of `.elc` files in it.  If I run `<M-x describe-key>` it works as expected.  `<M-x helpful-key>` also works as expected on my MacOS, it just doesn't want to work on Ubuntu for whatever reason.  Any ideas?

Steps to reproduce:

1) open a .org file
2) `<M-x helpful-key>`
3) Press a key, I've been doing `<C-return>`

Expect the proper help file

What happens instead is the error I described above below the mode-line area.

**Comment by Wilfred** [comment]
Interesting. I can't reproduce this on my Arch Linux box.

Would you mind doing `M-x toggle-debug-on-error` and pasting the backtrace?

**Comment by socketwiz** [comment]
Sure, here is the backtrace:
```
Debugger entered--Lisp error: (error "Can’t find library /usr/share/emacs/25.3/lisp/org/org")
  signal(error ("Can’t find library /usr/share/emacs/25.3/lisp/org/org"))
  error("Can't find library %s" "/usr/share/emacs/25.3/lisp/org/org")
  find-library-name("/usr/share/emacs/25.3/lisp/org/org.elc")
  helpful--definition(org-insert-heading-respect-content t)
  helpful--source(org-insert-heading-respect-content t)
  helpful-update()
  helpful-key([C-return])
  funcall-interactively(helpful-key [C-return])
  #<subr call-interactively>(helpful-key nil nil)
  apply(#<subr call-interactively> helpful-key (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> helpful-key nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (helpful-key nil nil))
  call-interactively(helpful-key nil nil)
  command-execute(helpful-key)
```
The file it appears it can't find certainly does exist:

```
$ ls -l /usr/share/emacs/25.3/lisp/org/org.elc
-rw-r--r-- 1 root root 798784 Sep 12 14:14 /usr/share/emacs/25.3/lisp/org/org.elc
```

**Comment by Wilfred** [comment]
Weird. OK, could you try evaluating the following? I've included the output in my Emacs for contrast.

```ELISP> (locate-file "/usr/share/emacs/25.3/lisp/org/org.el" load-path '("" ".gz"))
"/usr/share/emacs/25.3/lisp/org/org.el.gz"
ELISP> load-file-rep-suffixes
("" ".gz")
ELISP> find-function-source-path
nil
```

**Comment by socketwiz** [comment]
You'll have to bear with me, I'm no Emacs veteran by any means, I'm a vim user that just picked it up last summer.  However I did what I think you mean which is to run those two commands in the scratch buffer.
```elisp
(load-file-rep-suffixes)
("" ".gz")
(find-function-source-path)
nil
```
It would appear that I get the same results as you.

**Comment by socketwiz** [comment]
I "think" I fixed it.  I'm not an elisp expert but I decided to take a deeper look at that stack trace you had me get for you.  I know enough to know that the lines in the stack-trace that have underlines have source available so I navigated down to the first one:

``` elisp
 find-library-name("/usr/share/emacs/25.3/lisp/org/org.elc")
```

And when I keyed `<return>` on that line it said it could not find `/usr/share/emacs/25.3/lisp/emacs-lisp/find-func.el`.  I looked up that path with `ls` and while the `find-func.el` was not there, there was a `find-func.elc` file.  I googled something like "elisp .el missing" and came up with this page: 

https://emacs.stackexchange.com/questions/7184/where-are-emacs-lisp-files

I looked up what package might install the missing `.el` files with this command:

```
$ apt-cache search emacs25
```
And found `emacs25-el` which I promptly installed.  Now when I execute the steps to reproduce I posted above everything seems to work just fine.

I "think" the `.elc` file is supposed to be the compiled version of the `.el` file.  I'm not sure why it needed the uncompiled version but providing it seems to make it happy.  Maybe a few updates and things got out of sync or something and it needed the source to gets things lined back up.  I'm not sure that is just a guess, I'm still learning!

This seems like a reasonable solution to the problem so I'm going to close this ticket.  Thanks so much for your help.

**Comment by Wilfred** [comment]
Great debugging!

This means that Helpful crashes when you have a .elc without a .el file. We should be robust against this, so I'm going to leave this open.

**Comment by Wilfred** [comment]
You're correct, byte-compiling a file creates a .elc file from a .el file. Helpful tries to find the source code, but it hasn't been tested without a .el file, hence the bug :)

**Comment by Wilfred** [comment]
OK, this should be handled correctly in Helpful now. Thanks for your help with this!
