### ISSUE TITLE
Showing help in other window instead of pop-to-buffer?

### ISSUE THREAD

**Issue by publicimageltd** [Wilfred/helpful#90]
I kind of like the default behaviour that the help window is showing in an unfocused window, or at least, I am used to it. I suggest introducing a variable which defines whether calling the `helpful--`-functions with `pop-to-buffer` (as it is the case now) or, say, `switch-to-buffer-other-window`.

**Comment by Wilfred** [comment]
If you would like to submit a PR that defines something like a `helpful-switch-buffer-function` for this, that would be very welcome :)
